<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AccessLog;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserLastHour($phone_number)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb
			->select('al')
			->from('AppBundle\Entity\AccessLog', 'al')
			->where($qb->expr()->eq('al.phoneNumber', ':phone_number'))
			->andWhere(
				$qb->expr()->eq("DATE_FORMAT(al.dateCreated, '%Y-%m-%d %H')", "DATE_FORMAT(NOW(), '%Y-%m-%d %H')")
				)
			->setParameter('phone_number', $phone_number);

		return $query->getQuery()->getResult();
	}
}