fos_user:
    db_driver: orm
    firewall_name: api
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: UserBundle\Form\Type\RegistrationFormType
            name: app_user_registration
            validation_groups: [ my_registration, Default ]
        confirmation:
            enabled: false
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
