app:
    resource: '@AppBundle/Controller/'
    type: annotation

registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
