<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170613162920 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $date = new \DateTime('now');
        $dateString = $date->format('Y-m-d H:i:s');

        $countries = [
            ["name" => "Afghanistan", "iso" => "AF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Aland Islands", "iso" => "AX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Albania", "iso" => "AL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Algeria", "iso" => "DZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "American Samoa", "iso" => "AS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Andorra", "iso" => "AD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Angola", "iso" => "AO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Anguilla", "iso" => "AI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Antarctica", "iso" => "AQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Antigua and Barbuda", "iso" => "AG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Argentina", "iso" => "AR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Armenia", "iso" => "AM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Aruba", "iso" => "AW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Australia", "iso" => "AU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Austria", "iso" => "AT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Azerbaijan", "iso" => "AZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bahamas", "iso" => "BS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bahrain", "iso" => "BH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bangladesh", "iso" => "BD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Barbados", "iso" => "BB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Belarus", "iso" => "BY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Belgium", "iso" => "BE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Belize", "iso" => "BZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Benin", "iso" => "BJ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bermuda", "iso" => "BM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bhutan", "iso" => "BT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bolivia (Plurinational State of)", "iso" => "BO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bonaire, Sint Eustatius and Saba", "iso" => "BQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bosnia and Herzegovina", "iso" => "BA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Botswana", "iso" => "BW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bouvet Island", "iso" => "BV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Brazil", "iso" => "BR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "British Indian Ocean Territory", "iso" => "IO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "United States Minor Outlying Islands", "iso" => "UM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Virgin Islands (British)", "iso" => "VG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Virgin Islands (U.S.)", "iso" => "VI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Brunei Darussalam", "iso" => "BN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Bulgaria", "iso" => "BG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Burkina Faso", "iso" => "BF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Burundi", "iso" => "BI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cambodia", "iso" => "KH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cameroon", "iso" => "CM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Canada", "iso" => "CA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cabo Verde", "iso" => "CV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cayman Islands", "iso" => "KY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Central African Republic", "iso" => "CF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Chad", "iso" => "TD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Chile", "iso" => "CL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "China", "iso" => "CN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Christmas Island", "iso" => "CX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cocos (Keeling) Islands", "iso" => "CC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Colombia", "iso" => "CO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Comoros", "iso" => "KM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Congo", "iso" => "CG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Congo (Democratic Republic of the)", "iso" => "CD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cook Islands", "iso" => "CK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Costa Rica", "iso" => "CR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Croatia", "iso" => "HR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cuba", "iso" => "CU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cura\u00e7ao", "iso" => "CW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Cyprus", "iso" => "CY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Czech Republic", "iso" => "CZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Denmark", "iso" => "DK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Djibouti", "iso" => "DJ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Dominica", "iso" => "DM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Dominican Republic", "iso" => "DO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Ecuador", "iso" => "EC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Egypt", "iso" => "EG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "El Salvador", "iso" => "SV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Equatorial Guinea", "iso" => "GQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Eritrea", "iso" => "ER", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Estonia", "iso" => "EE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Ethiopia", "iso" => "ET", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Falkland Islands (Malvinas)", "iso" => "FK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Faroe Islands", "iso" => "FO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Fiji", "iso" => "FJ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Finland", "iso" => "FI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "France", "iso" => "FR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "French Guiana", "iso" => "GF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "French Polynesia", "iso" => "PF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "French Southern Territories", "iso" => "TF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Gabon", "iso" => "GA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Gambia", "iso" => "GM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Georgia", "iso" => "GE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Germany", "iso" => "DE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Ghana", "iso" => "GH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Gibraltar", "iso" => "GI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Greece", "iso" => "GR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Greenland", "iso" => "GL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Grenada", "iso" => "GD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guadeloupe", "iso" => "GP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guam", "iso" => "GU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guatemala", "iso" => "GT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guernsey", "iso" => "GG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guinea", "iso" => "GN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guinea-Bissau", "iso" => "GW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Guyana", "iso" => "GY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Haiti", "iso" => "HT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Heard Island and McDonald Islands", "iso" => "HM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Holy See", "iso" => "VA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Honduras", "iso" => "HN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Hong Kong", "iso" => "HK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Hungary", "iso" => "HU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Iceland", "iso" => "IS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "India", "iso" => "IN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Indonesia", "iso" => "ID", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "C\u00f4te d'Ivoire", "iso" => "CI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Iran (Islamic Republic of)", "iso" => "IR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Iraq", "iso" => "IQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Ireland", "iso" => "IE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Isle of Man", "iso" => "IM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Israel", "iso" => "IL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Italy", "iso" => "IT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Jamaica", "iso" => "JM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Japan", "iso" => "JP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Jersey", "iso" => "JE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Jordan", "iso" => "JO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Kazakhstan", "iso" => "K", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Kenya", "iso" => "KE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Kiribati", "iso" => "KI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Kuwait", "iso" => "KW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Kyrgyzstan", "iso" => "KG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Lao People's Democratic Republic", "iso" => "LA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Latvia", "iso" => "LV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Lebanon", "iso" => "LB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Lesotho", "iso" => "LS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Liberia", "iso" => "LR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Libya", "iso" => "LY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Liechtenstein", "iso" => "LI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Lithuania", "iso" => "LT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Luxembourg", "iso" => "LU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Macao", "iso" => "MO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Macedonia (the former Yugoslav Republic of)", "iso" => "MK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Madagascar", "iso" => "MG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Malawi", "iso" => "MW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Malaysia", "iso" => "MY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Maldives", "iso" => "MV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mali", "iso" => "ML", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Malta", "iso" => "MT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Marshall Islands", "iso" => "MH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Martinique", "iso" => "MQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mauritania", "iso" => "MR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mauritius", "iso" => "MU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mayotte", "iso" => "YT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mexico", "iso" => "MX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Micronesia (Federated States of)", "iso" => "FM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Moldova (Republic of)", "iso" => "MD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Monaco", "iso" => "MC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mongolia", "iso" => "MN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Montenegro", "iso" => "ME", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Montserrat", "iso" => "MS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Morocco", "iso" => "MA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Mozambique", "iso" => "MZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Myanmar", "iso" => "MM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Namibia", "iso" => "NA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Nauru", "iso" => "NR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Nepal", "iso" => "NP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Netherlands", "iso" => "NL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "New Caledonia", "iso" => "NC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "New Zealand", "iso" => "NZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Nicaragua", "iso" => "NI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Niger", "iso" => "NE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Nigeria", "iso" => "NG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Niue", "iso" => "NU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Norfolk Island", "iso" => "NF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Korea (Democratic People's Republic of)", "iso" => "KP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Northern Mariana Islands", "iso" => "MP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Norway", "iso" => "NO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Oman", "iso" => "OM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Pakistan", "iso" => "PK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Palau", "iso" => "PW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Palestine, State of", "iso" => "PS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Panama", "iso" => "PA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Papua New Guinea", "iso" => "PG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Paraguay", "iso" => "PY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Peru", "iso" => "PE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Philippines", "iso" => "PH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Pitcairn", "iso" => "PN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Poland", "iso" => "PL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Portugal", "iso" => "PT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Puerto Rico", "iso" => "PR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Qatar", "iso" => "QA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Republic of Kosovo", "iso" => "XK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "R\u00e9union", "iso" => "RE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Romania", "iso" => "RO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Russian Federation", "iso" => "RU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Rwanda", "iso" => "RW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Barth\u00e9lemy", "iso" => "BL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Helena, Ascension and Tristan da Cunha", "iso" => "SH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Kitts and Nevis", "iso" => "KN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Lucia", "iso" => "LC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Martin (French part)", "iso" => "MF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],  
            ["name" => "Saint Pierre and Miquelon", "iso" => "PM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saint Vincent and the Grenadines", "iso" => "VC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Samoa", "iso" => "WS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "San Marino", "iso" => "SM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sao Tome and Principe", "iso" => "ST", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Saudi Arabia", "iso" => "SA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Senegal", "iso" => "SN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Serbia", "iso" => "RS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Seychelles", "iso" => "SC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sierra Leone", "iso" => "SL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Singapore", "iso" => "SG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sint Maarten (Dutch part)", "iso" => "SX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Slovakia", "iso" => "SK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Slovenia", "iso" => "SI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Solomon Islands", "iso" => "SB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Somalia", "iso" => "SO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "South Africa", "iso" => "ZA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "South Georgia and the South Sandwich Islands", "iso" => "GS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Korea (Republic of)", "iso" => "KR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "South Sudan", "iso" => "SS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Spain", "iso" => "ES", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sri Lanka", "iso" => "LK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sudan", "iso" => "SD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Suriname", "iso" => "SR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Svalbard and Jan Mayen", "iso" => "SJ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Swaziland", "iso" => "SZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Sweden", "iso" => "SE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Switzerland", "iso" => "CH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Syrian Arab Republic", "iso" => "SY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Taiwan, Province of China", "iso" => "TW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tajikistan", "iso" => "TJ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tanzania, United Republic of", "iso" => "TZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Thailand", "iso" => "TH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Timor-Leste", "iso" => "TL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Togo", "iso" => "TG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tokelau", "iso" => "TK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tonga", "iso" => "TO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Trinidad and Tobago", "iso" => "TT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tunisia", "iso" => "TN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Turkey", "iso" => "TR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Turkmenistan", "iso" => "TM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Turks and Caicos Islands", "iso" => "TC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Tuvalu", "iso" => "TV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Uganda", "iso" => "UG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Ukraine", "iso" => "UA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "United Arab Emirates", "iso" => "AE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "United Kingdom of Great Britain and Northern Ireland", "iso" => "GB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "United States of America", "iso" => "US", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Uruguay", "iso" => "UY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Uzbekistan", "iso" => "UZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Vanuatu", "iso" => "VU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Venezuela (Bolivarian Republic of)", "iso" => "VE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Viet Nam", "iso" => "VN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Wallis and Futuna", "iso" => "WF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Western Sahara", "iso" => "EH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Yemen", "iso" => "YE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Zambia", "iso" => "ZM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name" => "Zimbabwe", "iso" => "ZW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString]
        ];

        foreach($countries as $country){
            $this->connection->insert('Countries', $country);
        }
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
