<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration=> Please modify to your needs!
 */
class Version20170613162920 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $date = new \DateTime('now');
        $dateString = $date->format('Y-m-d H=>i=>s');

        $countries = [
            ["name"=>"Afghanistan", "iso2"=>"AF", "iso3"=>"AFG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Åland Islands", "iso2"=>"AX", "iso3"=>"ALA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Albania", "iso2"=>"AL", "iso3"=>"ALB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Algeria", "iso2"=>"DZ", "iso3"=>"DZA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"American Samoa", "iso2"=>"AS", "iso3"=>"ASM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Andorra", "iso2"=>"AD", "iso3"=>"AND", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Angola", "iso2"=>"AO", "iso3"=>"AGO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Anguilla", "iso2"=>"AI", "iso3"=>"AIA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Antarctica", "iso2"=>"AQ", "iso3"=>"ATA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Antigua and Barbuda", "iso2"=>"AG", "iso3"=>"ATG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Argentina", "iso2"=>"AR", "iso3"=>"ARG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Armenia", "iso2"=>"AM", "iso3"=>"ARM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Aruba", "iso2"=>"AW", "iso3"=>"ABW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Australia", "iso2"=>"AU", "iso3"=>"AUS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Austria", "iso2"=>"AT", "iso3"=>"AUT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Azerbaijan", "iso2"=>"AZ", "iso3"=>"AZE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bahamas", "iso2"=>"BS", "iso3"=>"BHS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bahrain", "iso2"=>"BH", "iso3"=>"BHR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bangladesh", "iso2"=>"BD", "iso3"=>"BGD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Barbados", "iso2"=>"BB", "iso3"=>"BRB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Belarus", "iso2"=>"BY", "iso3"=>"BLR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Belgium", "iso2"=>"BE", "iso3"=>"BEL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Belize", "iso2"=>"BZ", "iso3"=>"BLZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Benin", "iso2"=>"BJ", "iso3"=>"BEN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bermuda", "iso2"=>"BM", "iso3"=>"BMU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bhutan", "iso2"=>"BT", "iso3"=>"BTN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bolivia (Plurinational State of)", "iso2"=>"BO", "iso3"=>"BOL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bonaire, Sint Eustatius and Saba", "iso2"=>"BQ", "iso3"=>"BES", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bosnia and Herzegovina", "iso2"=>"BA", "iso3"=>"BIH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Botswana", "iso2"=>"BW", "iso3"=>"BWA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bouvet Island", "iso2"=>"BV", "iso3"=>"BVT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Brazil", "iso2"=>"BR", "iso3"=>"BRA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"British Indian Ocean Territory", "iso2"=>"IO", "iso3"=>"IOT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"United States Minor Outlying Islands", "iso2"=>"UM", "iso3"=>"UMI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Virgin Islands (British)", "iso2"=>"VG", "iso3"=>"VGB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Virgin Islands (U.S.)", "iso2"=>"VI", "iso3"=>"VIR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Brunei Darussalam", "iso2"=>"BN", "iso3"=>"BRN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Bulgaria", "iso2"=>"BG", "iso3"=>"BGR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Burkina Faso", "iso2"=>"BF", "iso3"=>"BFA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Burundi", "iso2"=>"BI", "iso3"=>"BDI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cambodia", "iso2"=>"KH", "iso3"=>"KHM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cameroon", "iso2"=>"CM", "iso3"=>"CMR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Canada", "iso2"=>"CA", "iso3"=>"CAN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cabo Verde", "iso2"=>"CV", "iso3"=>"CPV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cayman Islands", "iso2"=>"KY", "iso3"=>"CYM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Chad", "iso2"=>"TD", "iso3"=>"TCD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Chile", "iso2"=>"CL", "iso3"=>"CHL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"China", "iso2"=>"CN", "iso3"=>"CHN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Christmas Island", "iso2"=>"CX", "iso3"=>"CXR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cocos (Keeling) Islands", "iso2"=>"CC", "iso3"=>"CCK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Colombia", "iso2"=>"CO", "iso3"=>"COL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Comoros", "iso2"=>"KM", "iso3"=>"COM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Congo", "iso2"=>"CG", "iso3"=>"COG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Congo (Democratic Republic of the)", "iso2"=>"CD", "iso3"=>"COD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cook Islands", "iso2"=>"CK", "iso3"=>"COK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Costa Rica", "iso2"=>"CR", "iso3"=>"CRI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Croatia", "iso2"=>"HR", "iso3"=>"HRV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cuba", "iso2"=>"CU", "iso3"=>"CUB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Curaçao", "iso2"=>"CW", "iso3"=>"CUW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Cyprus", "iso2"=>"CY", "iso3"=>"CYP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Czech Republic", "iso2"=>"CZ", "iso3"=>"CZE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Denmark", "iso2"=>"DK", "iso3"=>"DNK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Djibouti", "iso2"=>"DJ", "iso3"=>"DJI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Dominica", "iso2"=>"DM", "iso3"=>"DMA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Dominican Republic", "iso2"=>"DO", "iso3"=>"DOM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Ecuador", "iso2"=>"EC", "iso3"=>"ECU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Egypt", "iso2"=>"EG", "iso3"=>"EGY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"El Salvador", "iso2"=>"SV", "iso3"=>"SLV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Equatorial Guinea", "iso2"=>"GQ", "iso3"=>"GNQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Eritrea", "iso2"=>"ER", "iso3"=>"ERI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Estonia", "iso2"=>"EE", "iso3"=>"EST", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Ethiopia", "iso2"=>"ET", "iso3"=>"ETH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Falkland Islands (Malvinas)", "iso2"=>"FK", "iso3"=>"FLK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Faroe Islands", "iso2"=>"FO", "iso3"=>"FRO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Fiji", "iso2"=>"FJ", "iso3"=>"FJI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Finland", "iso2"=>"FI", "iso3"=>"FIN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"France", "iso2"=>"FR", "iso3"=>"FRA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"French Guiana", "iso2"=>"GF", "iso3"=>"GUF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"French Polynesia", "iso2"=>"PF", "iso3"=>"PYF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"French Southern Territories", "iso2"=>"TF", "iso3"=>"ATF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Gabon", "iso2"=>"GA", "iso3"=>"GAB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Gambia", "iso2"=>"GM", "iso3"=>"GMB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Georgia", "iso2"=>"GE", "iso3"=>"GEO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Germany", "iso2"=>"DE", "iso3"=>"DEU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Ghana", "iso2"=>"GH", "iso3"=>"GHA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Gibraltar", "iso2"=>"GI", "iso3"=>"GIB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Greece", "iso2"=>"GR", "iso3"=>"GRC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Greenland", "iso2"=>"GL", "iso3"=>"GRL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Grenada", "iso2"=>"GD", "iso3"=>"GRD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guadeloupe", "iso2"=>"GP", "iso3"=>"GLP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guam", "iso2"=>"GU", "iso3"=>"GUM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guatemala", "iso2"=>"GT", "iso3"=>"GTM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guernsey", "iso2"=>"GG", "iso3"=>"GGY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guinea", "iso2"=>"GN", "iso3"=>"GIN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guinea-Bissau", "iso2"=>"GW", "iso3"=>"GNB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Guyana", "iso2"=>"GY", "iso3"=>"GUY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Haiti", "iso2"=>"HT", "iso3"=>"HTI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Heard Island and McDonald Islands", "iso2"=>"HM", "iso3"=>"HMD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Holy See", "iso2"=>"VA", "iso3"=>"VAT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Honduras", "iso2"=>"HN", "iso3"=>"HND", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Hong Kong", "iso2"=>"HK", "iso3"=>"HKG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Hungary", "iso2"=>"HU", "iso3"=>"HUN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Iceland", "iso2"=>"IS", "iso3"=>"ISL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"India", "iso2"=>"IN", "iso3"=>"IND", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Indonesia", "iso2"=>"ID", "iso3"=>"IDN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Côte d'Ivoire", "iso2"=>"CI", "iso3"=>"CIV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Iran (Islamic Republic of)", "iso2"=>"IR", "iso3"=>"IRN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Iraq", "iso2"=>"IQ", "iso3"=>"IRQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Ireland", "iso2"=>"IE", "iso3"=>"IRL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Isle of Man", "iso2"=>"IM", "iso3"=>"IMN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Israel", "iso2"=>"IL", "iso3"=>"ISR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Italy", "iso2"=>"IT", "iso3"=>"ITA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Jamaica", "iso2"=>"JM", "iso3"=>"JAM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Japan", "iso2"=>"JP", "iso3"=>"JPN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Jersey", "iso2"=>"JE", "iso3"=>"JEY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Jordan", "iso2"=>"JO", "iso3"=>"JOR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Kazakhstan", "iso2"=>"KZ", "iso3"=>"KAZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Kenya", "iso2"=>"KE", "iso3"=>"KEN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Kiribati", "iso2"=>"KI", "iso3"=>"KIR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Kuwait", "iso2"=>"KW", "iso3"=>"KWT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Kyrgyzstan", "iso2"=>"KG", "iso3"=>"KGZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Lao People's Democratic Republic", "iso2"=>"LA", "iso3"=>"LAO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Latvia", "iso2"=>"LV", "iso3"=>"LVA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Lebanon", "iso2"=>"LB", "iso3"=>"LBN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Lesotho", "iso2"=>"LS", "iso3"=>"LSO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Liberia", "iso2"=>"LR", "iso3"=>"LBR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Libya", "iso2"=>"LY", "iso3"=>"LBY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Liechtenstein", "iso2"=>"LI", "iso3"=>"LIE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Lithuania", "iso2"=>"LT", "iso3"=>"LTU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Luxembourg", "iso2"=>"LU", "iso3"=>"LUX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Macao", "iso2"=>"MO", "iso3"=>"MAC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Macedonia (the former Yugoslav Republic of)", "iso2"=>"MK", "iso3"=>"MKD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Madagascar", "iso2"=>"MG", "iso3"=>"MDG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Malawi", "iso2"=>"MW", "iso3"=>"MWI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Malaysia", "iso2"=>"MY", "iso3"=>"MYS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Maldives", "iso2"=>"MV", "iso3"=>"MDV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mali", "iso2"=>"ML", "iso3"=>"MLI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Malta", "iso2"=>"MT", "iso3"=>"MLT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Marshall Islands", "iso2"=>"MH", "iso3"=>"MHL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Martinique", "iso2"=>"MQ", "iso3"=>"MTQ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mauritania", "iso2"=>"MR", "iso3"=>"MRT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mauritius", "iso2"=>"MU", "iso3"=>"MUS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mayotte", "iso2"=>"YT", "iso3"=>"MYT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mexico", "iso2"=>"MX", "iso3"=>"MEX", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Micronesia (Federated States of)", "iso2"=>"FM", "iso3"=>"FSM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Moldova (Republic of)", "iso2"=>"MD", "iso3"=>"MDA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Monaco", "iso2"=>"MC", "iso3"=>"MCO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mongolia", "iso2"=>"MN", "iso3"=>"MNG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Montenegro", "iso2"=>"ME", "iso3"=>"MNE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Montserrat", "iso2"=>"MS", "iso3"=>"MSR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Morocco", "iso2"=>"MA", "iso3"=>"MAR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Mozambique", "iso2"=>"MZ", "iso3"=>"MOZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Myanmar", "iso2"=>"MM", "iso3"=>"MMR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Namibia", "iso2"=>"NA", "iso3"=>"NAM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Nauru", "iso2"=>"NR", "iso3"=>"NRU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Nepal", "iso2"=>"NP", "iso3"=>"NPL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Netherlands", "iso2"=>"NL", "iso3"=>"NLD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"New Caledonia", "iso2"=>"NC", "iso3"=>"NCL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"New Zealand", "iso2"=>"NZ", "iso3"=>"NZL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Nicaragua", "iso2"=>"NI", "iso3"=>"NIC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Niger", "iso2"=>"NE", "iso3"=>"NER", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Nigeria", "iso2"=>"NG", "iso3"=>"NGA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Niue", "iso2"=>"NU", "iso3"=>"NIU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Norfolk Island", "iso2"=>"NF", "iso3"=>"NFK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Korea (Democratic People's Republic of)", "iso2"=>"KP", "iso3"=>"PRK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Northern Mariana Islands", "iso2"=>"MP", "iso3"=>"MNP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Norway", "iso2"=>"NO", "iso3"=>"NOR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Oman", "iso2"=>"OM", "iso3"=>"OMN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Pakistan", "iso2"=>"PK", "iso3"=>"PAK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Palau", "iso2"=>"PW", "iso3"=>"PLW", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Palestine, State of", "iso2"=>"PS", "iso3"=>"PSE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Panama", "iso2"=>"PA", "iso3"=>"PAN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Papua New Guinea", "iso2"=>"PG", "iso3"=>"PNG", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Paraguay", "iso2"=>"PY", "iso3"=>"PRY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Peru", "iso2"=>"PE", "iso3"=>"PER", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Philippines", "iso2"=>"PH", "iso3"=>"PHL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Pitcairn", "iso2"=>"PN", "iso3"=>"PCN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Poland", "iso2"=>"PL", "iso3"=>"POL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Portugal", "iso2"=>"PT", "iso3"=>"PRT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Puerto Rico", "iso2"=>"PR", "iso3"=>"PRI", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Qatar", "iso2"=>"QA", "iso3"=>"QAT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Republic of Kosovo", "iso2"=>"XK", "iso3"=>"KOS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Réunion", "iso2"=>"RE", "iso3"=>"REU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Romania", "iso2"=>"RO", "iso3"=>"ROU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Russian Federation", "iso2"=>"RU", "iso3"=>"RUS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Rwanda", "iso2"=>"RW", "iso3"=>"RWA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Barthélemy", "iso2"=>"BL", "iso3"=>"BLM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Helena, Ascension and Tristan da Cunha", "iso2"=>"SH", "iso3"=>"SHN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Kitts and Nevis", "iso2"=>"KN", "iso3"=>"KNA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Lucia", "iso2"=>"LC", "iso3"=>"LCA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Martin (French part)", "iso2"=>"MF", "iso3"=>"MAF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Pierre and Miquelon", "iso2"=>"PM", "iso3"=>"SPM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saint Vincent and the Grenadines", "iso2"=>"VC", "iso3"=>"VCT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Samoa", "iso2"=>"WS", "iso3"=>"WSM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"San Marino", "iso2"=>"SM", "iso3"=>"SMR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sao Tome and Principe", "iso2"=>"ST", "iso3"=>"STP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Saudi Arabia", "iso2"=>"SA", "iso3"=>"SAU", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Senegal", "iso2"=>"SN", "iso3"=>"SEN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Serbia", "iso2"=>"RS", "iso3"=>"SRB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Seychelles", "iso2"=>"SC", "iso3"=>"SYC", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sierra Leone", "iso2"=>"SL", "iso3"=>"SLE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Singapore", "iso2"=>"SG", "iso3"=>"SGP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sint Maarten (Dutch part)", "iso2"=>"SX", "iso3"=>"SXM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Slovakia", "iso2"=>"SK", "iso3"=>"SVK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Slovenia", "iso2"=>"SI", "iso3"=>"SVN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Solomon Islands", "iso2"=>"SB", "iso3"=>"SLB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Somalia", "iso2"=>"SO", "iso3"=>"SOM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"South Africa", "iso2"=>"ZA", "iso3"=>"ZAF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"South Georgia and the South Sandwich Islands", "iso2"=>"GS", "iso3"=>"SGS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Korea (Republic of)", "iso2"=>"KR", "iso3"=>"KOR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"South Sudan", "iso2"=>"SS", "iso3"=>"SSD", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Spain", "iso2"=>"ES", "iso3"=>"ESP", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sri Lanka", "iso2"=>"LK", "iso3"=>"LKA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sudan", "iso2"=>"SD", "iso3"=>"SDN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Suriname", "iso2"=>"SR", "iso3"=>"SUR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Svalbard and Jan Mayen", "iso2"=>"SJ", "iso3"=>"SJM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Swaziland", "iso2"=>"SZ", "iso3"=>"SWZ", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Sweden", "iso2"=>"SE", "iso3"=>"SWE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Switzerland", "iso2"=>"CH", "iso3"=>"CHE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Syrian Arab Republic", "iso2"=>"SY", "iso3"=>"SYR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Taiwan, Province of China", "iso2"=>"TW", "iso3"=>"TWN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tajikistan", "iso2"=>"TJ", "iso3"=>"TJK", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tanzania, United Republic of", "iso2"=>"TZ", "iso3"=>"TZA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Thailand", "iso2"=>"TH", "iso3"=>"THA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Timor-Leste", "iso2"=>"TL", "iso3"=>"TLS", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Togo", "iso2"=>"TG", "iso3"=>"TGO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tokelau", "iso2"=>"TK", "iso3"=>"TKL", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tonga", "iso2"=>"TO", "iso3"=>"TON", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Trinidad and Tobago", "iso2"=>"TT", "iso3"=>"TTO", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tunisia", "iso2"=>"TN", "iso3"=>"TUN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Turkey", "iso2"=>"TR", "iso3"=>"TUR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Turkmenistan", "iso2"=>"TM", "iso3"=>"TKM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Turks and Caicos Islands", "iso2"=>"TC", "iso3"=>"TCA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Tuvalu", "iso2"=>"TV", "iso3"=>"TUV", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Uganda", "iso2"=>"UG", "iso3"=>"UGA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Ukraine", "iso2"=>"UA", "iso3"=>"UKR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"United Arab Emirates", "iso2"=>"AE", "iso3"=>"ARE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"United Kingdom of Great Britain and Northern Ireland", "iso2"=>"GB", "iso3"=>"GBR", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"United States of America", "iso2"=>"US", "iso3"=>"USA", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Uruguay", "iso2"=>"UY", "iso3"=>"URY", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Uzbekistan", "iso2"=>"UZ", "iso3"=>"UZB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Vanuatu", "iso2"=>"VU", "iso3"=>"VUT", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Venezuela (Bolivarian Republic of)", "iso2"=>"VE", "iso3"=>"VEN", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Viet Nam", "iso2"=>"VN", "iso3"=>"VNM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Wallis and Futuna", "iso2"=>"WF", "iso3"=>"WLF", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Western Sahara", "iso2"=>"EH", "iso3"=>"ESH", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Yemen", "iso2"=>"YE", "iso3"=>"YEM", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Zambia", "iso2"=>"ZM", "iso3"=>"ZMB", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ["name"=>"Zimbabwe", "iso2"=>"ZW", "iso3"=>"ZWE", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString]
        ];

        foreach($countries as $country){
            $this->connection->insert('Countries', $country);
        }
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
