<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration=> Please modify to your needs!
 */
class Version20170613162920 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $date = new \DateTime('now');
        $dateString = $date->format('Y-m-d H=>i=>s');

        $countries = [
            ['name' => "Afghanistan", 'iso2' => "AF", 'iso3' => "AFG", 'iso_numeric' => "004", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Åland Islands", 'iso2' => "AX", 'iso3' => "ALA", 'iso_numeric' => "248", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Albania", 'iso2' => "AL", 'iso3' => "ALB", 'iso_numeric' => "008", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Algeria", 'iso2' => "DZ", 'iso3' => "DZA", 'iso_numeric' => "012", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "American Samoa", 'iso2' => "AS", 'iso3' => "ASM", 'iso_numeric' => "016", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Andorra", 'iso2' => "AD", 'iso3' => "AND", 'iso_numeric' => "020", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Angola", 'iso2' => "AO", 'iso3' => "AGO", 'iso_numeric' => "024", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Anguilla", 'iso2' => "AI", 'iso3' => "AIA", 'iso_numeric' => "660", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Antarctica", 'iso2' => "AQ", 'iso3' => "ATA", 'iso_numeric' => "010", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Antigua and Barbuda", 'iso2' => "AG", 'iso3' => "ATG", 'iso_numeric' => "028", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Argentina", 'iso2' => "AR", 'iso3' => "ARG", 'iso_numeric' => "032", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Armenia", 'iso2' => "AM", 'iso3' => "ARM", 'iso_numeric' => "051", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Aruba", 'iso2' => "AW", 'iso3' => "ABW", 'iso_numeric' => "533", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Australia", 'iso2' => "AU", 'iso3' => "AUS", 'iso_numeric' => "036", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Austria", 'iso2' => "AT", 'iso3' => "AUT", 'iso_numeric' => "040", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Azerbaijan", 'iso2' => "AZ", 'iso3' => "AZE", 'iso_numeric' => "031", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bahamas", 'iso2' => "BS", 'iso3' => "BHS", 'iso_numeric' => "044", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bahrain", 'iso2' => "BH", 'iso3' => "BHR", 'iso_numeric' => "048", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bangladesh", 'iso2' => "BD", 'iso3' => "BGD", 'iso_numeric' => "050", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Barbados", 'iso2' => "BB", 'iso3' => "BRB", 'iso_numeric' => "052", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Belarus", 'iso2' => "BY", 'iso3' => "BLR", 'iso_numeric' => "112", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Belgium", 'iso2' => "BE", 'iso3' => "BEL", 'iso_numeric' => "056", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Belize", 'iso2' => "BZ", 'iso3' => "BLZ", 'iso_numeric' => "084", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Benin", 'iso2' => "BJ", 'iso3' => "BEN", 'iso_numeric' => "204", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bermuda", 'iso2' => "BM", 'iso3' => "BMU", 'iso_numeric' => "060", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bhutan", 'iso2' => "BT", 'iso3' => "BTN", 'iso_numeric' => "064", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bolivia (Plurinational State of)", 'iso2' => "BO", 'iso3' => "BOL", 'iso_numeric' => "068", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bonaire, 'iso2' => Sint Eustatius and Saba", 'iso2' => "BQ", 'iso3' => "BES", 'iso_numeric' => "535", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bosnia and Herzegovina", 'iso2' => "BA", 'iso3' => "BIH", 'iso_numeric' => "070", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Botswana", 'iso2' => "BW", 'iso3' => "BWA", 'iso_numeric' => "072", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bouvet Island", 'iso2' => "BV", 'iso3' => "BVT", 'iso_numeric' => "074", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Brazil", 'iso2' => "BR", 'iso3' => "BRA", 'iso_numeric' => "076", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "British Indian Ocean Territory", 'iso2' => "IO", 'iso3' => "IOT", 'iso_numeric' => "086", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Brunei Darussalam", 'iso2' => "BN", 'iso3' => "BRN", 'iso_numeric' => "096", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Bulgaria", 'iso2' => "BG", 'iso3' => "BGR", 'iso_numeric' => "100", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Burkina Faso", 'iso2' => "BF", 'iso3' => "BFA", 'iso_numeric' => "854", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Burundi", 'iso2' => "BI", 'iso3' => "BDI", 'iso_numeric' => "108", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cabo Verde", 'iso2' => "CV", 'iso3' => "CPV", 'iso_numeric' => "132", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cambodia", 'iso2' => "KH", 'iso3' => "KHM", 'iso_numeric' => "116", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cameroon", 'iso2' => "CM", 'iso3' => "CMR", 'iso_numeric' => "120", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Canada", 'iso2' => "CA", 'iso3' => "CAN", 'iso_numeric' => "124", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cayman Islands", 'iso2' => "KY", 'iso3' => "CYM", 'iso_numeric' => "136", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Central African Republic", 'iso2' => "CF", 'iso3' => "CAF", 'iso_numeric' => "140", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Chad", 'iso2' => "TD", 'iso3' => "TCD", 'iso_numeric' => "148", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Chile", 'iso2' => "CL", 'iso3' => "CHL", 'iso_numeric' => "152", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "China", 'iso2' => "CN", 'iso3' => "CHN", 'iso_numeric' => "156", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Christmas Island", 'iso2' => "CX", 'iso3' => "CXR", 'iso_numeric' => "162", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cocos (Keeling) Islands", 'iso2' => "CC", 'iso3' => "CCK", 'iso_numeric' => "166", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Colombia", 'iso2' => "CO", 'iso3' => "COL", 'iso_numeric' => "170", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Comoros", 'iso2' => "KM", 'iso3' => "COM", 'iso_numeric' => "174", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Congo", 'iso2' => "CG", 'iso3' => "COG", 'iso_numeric' => "178", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Congo (Democratic Republic of the)", 'iso2' => "CD", 'iso3' => "COD", 'iso_numeric' => "180", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cook Islands", 'iso2' => "CK", 'iso3' => "COK", 'iso_numeric' => "184", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Costa Rica", 'iso2' => "CR", 'iso3' => "CRI", 'iso_numeric' => "188", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Côte d'Ivoire", 'iso2' => "CI", 'iso3' => "CIV", 'iso_numeric' => "384", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Croatia", 'iso2' => "HR", 'iso3' => "HRV", 'iso_numeric' => "191", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cuba", 'iso2' => "CU", 'iso3' => "CUB", 'iso_numeric' => "192", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Curaçao", 'iso2' => "CW", 'iso3' => "CUW", 'iso_numeric' => "531", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Cyprus", 'iso2' => "CY", 'iso3' => "CYP", 'iso_numeric' => "196", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Czechia", 'iso2' => "CZ", 'iso3' => "CZE", 'iso_numeric' => "203", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Denmark", 'iso2' => "DK", 'iso3' => "DNK", 'iso_numeric' => "208", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Djibouti", 'iso2' => "DJ", 'iso3' => "DJI", 'iso_numeric' => "262", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Dominica", 'iso2' => "DM", 'iso3' => "DMA", 'iso_numeric' => "212", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Dominican Republic", 'iso2' => "DO", 'iso3' => "DOM", 'iso_numeric' => "214", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Ecuador", 'iso2' => "EC", 'iso3' => "ECU", 'iso_numeric' => "218", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Egypt", 'iso2' => "EG", 'iso3' => "EGY", 'iso_numeric' => "818", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "El Salvador", 'iso2' => "SV", 'iso3' => "SLV", 'iso_numeric' => "222", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Equatorial Guinea", 'iso2' => "GQ", 'iso3' => "GNQ", 'iso_numeric' => "226", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Eritrea", 'iso2' => "ER", 'iso3' => "ERI", 'iso_numeric' => "232", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Estonia", 'iso2' => "EE", 'iso3' => "EST", 'iso_numeric' => "233", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Ethiopia", 'iso2' => "ET", 'iso3' => "ETH", 'iso_numeric' => "231", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Falkland Islands (Malvinas)", 'iso2' => "FK", 'iso3' => "FLK", 'iso_numeric' => "238", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Faroe Islands", 'iso2' => "FO", 'iso3' => "FRO", 'iso_numeric' => "234", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Fiji", 'iso2' => "FJ", 'iso3' => "FJI", 'iso_numeric' => "242", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Finland", 'iso2' => "FI", 'iso3' => "FIN", 'iso_numeric' => "246", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "France", 'iso2' => "FR", 'iso3' => "FRA", 'iso_numeric' => "250", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "French Guiana", 'iso2' => "GF", 'iso3' => "GUF", 'iso_numeric' => "254", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "French Polynesia", 'iso2' => "PF", 'iso3' => "PYF", 'iso_numeric' => "258", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "French Southern Territories", 'iso2' => "TF", 'iso3' => "ATF", 'iso_numeric' => "260", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Gabon", 'iso2' => "GA", 'iso3' => "GAB", 'iso_numeric' => "266", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Gambia", 'iso2' => "GM", 'iso3' => "GMB", 'iso_numeric' => "270", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Georgia", 'iso2' => "GE", 'iso3' => "GEO", 'iso_numeric' => "268", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Germany", 'iso2' => "DE", 'iso3' => "DEU", 'iso_numeric' => "276", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Ghana", 'iso2' => "GH", 'iso3' => "GHA", 'iso_numeric' => "288", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Gibraltar", 'iso2' => "GI", 'iso3' => "GIB", 'iso_numeric' => "292", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Greece", 'iso2' => "GR", 'iso3' => "GRC", 'iso_numeric' => "300", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Greenland", 'iso2' => "GL", 'iso3' => "GRL", 'iso_numeric' => "304", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Grenada", 'iso2' => "GD", 'iso3' => "GRD", 'iso_numeric' => "308", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guadeloupe", 'iso2' => "GP", 'iso3' => "GLP", 'iso_numeric' => "312", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guam", 'iso2' => "GU", 'iso3' => "GUM", 'iso_numeric' => "316", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guatemala", 'iso2' => "GT", 'iso3' => "GTM", 'iso_numeric' => "320", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guernsey", 'iso2' => "GG", 'iso3' => "GGY", 'iso_numeric' => "831", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guinea", 'iso2' => "GN", 'iso3' => "GIN", 'iso_numeric' => "324", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guinea-Bissau", 'iso2' => "GW", 'iso3' => "GNB", 'iso_numeric' => "624", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Guyana", 'iso2' => "GY", 'iso3' => "GUY", 'iso_numeric' => "328", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Haiti", 'iso2' => "HT", 'iso3' => "HTI", 'iso_numeric' => "332", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Heard Island and McDonald Islands", 'iso2' => "HM", 'iso3' => "HMD", 'iso_numeric' => "334", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Holy See", 'iso2' => "VA", 'iso3' => "VAT", 'iso_numeric' => "336", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Honduras", 'iso2' => "HN", 'iso3' => "HND", 'iso_numeric' => "340", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Hong Kong", 'iso2' => "HK", 'iso3' => "HKG", 'iso_numeric' => "344", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Hungary", 'iso2' => "HU", 'iso3' => "HUN", 'iso_numeric' => "348", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Iceland", 'iso2' => "IS", 'iso3' => "ISL", 'iso_numeric' => "352", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "India", 'iso2' => "IN", 'iso3' => "IND", 'iso_numeric' => "356", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Indonesia", 'iso2' => "ID", 'iso3' => "IDN", 'iso_numeric' => "360", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Iran (Islamic Republic of)", 'iso2' => "IR", 'iso3' => "IRN", 'iso_numeric' => "364", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Iraq", 'iso2' => "IQ", 'iso3' => "IRQ", 'iso_numeric' => "368", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Ireland", 'iso2' => "IE", 'iso3' => "IRL", 'iso_numeric' => "372", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Isle of Man", 'iso2' => "IM", 'iso3' => "IMN", 'iso_numeric' => "833", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Israel", 'iso2' => "IL", 'iso3' => "ISR", 'iso_numeric' => "376", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Italy", 'iso2' => "IT", 'iso3' => "ITA", 'iso_numeric' => "380", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Jamaica", 'iso2' => "JM", 'iso3' => "JAM", 'iso_numeric' => "388", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Japan", 'iso2' => "JP", 'iso3' => "JPN", 'iso_numeric' => "392", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Jersey", 'iso2' => "JE", 'iso3' => "JEY", 'iso_numeric' => "832", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Jordan", 'iso2' => "JO", 'iso3' => "JOR", 'iso_numeric' => "400", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Kazakhstan", 'iso2' => "KZ", 'iso3' => "KAZ", 'iso_numeric' => "398", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Kenya", 'iso2' => "KE", 'iso3' => "KEN", 'iso_numeric' => "404", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Kiribati", 'iso2' => "KI", 'iso3' => "KIR", 'iso_numeric' => "296", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Korea (Democratic People's Republic of)", 'iso2' => "KP", 'iso3' => "PRK", 'iso_numeric' => "408", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Korea (Republic of)", 'iso2' => "KR", 'iso3' => "KOR", 'iso_numeric' => "410", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Kuwait", 'iso2' => "KW", 'iso3' => "KWT", 'iso_numeric' => "414", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Kyrgyzstan", 'iso2' => "KG", 'iso3' => "KGZ", 'iso_numeric' => "417", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Lao People's Democratic Republic", 'iso2' => "LA", 'iso3' => "LAO", 'iso_numeric' => "418", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Latvia", 'iso2' => "LV", 'iso3' => "LVA", 'iso_numeric' => "428", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Lebanon", 'iso2' => "LB", 'iso3' => "LBN", 'iso_numeric' => "422", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Lesotho", 'iso2' => "LS", 'iso3' => "LSO", 'iso_numeric' => "426", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Liberia", 'iso2' => "LR", 'iso3' => "LBR", 'iso_numeric' => "430", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Libya", 'iso2' => "LY", 'iso3' => "LBY", 'iso_numeric' => "434", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Liechtenstein", 'iso2' => "LI", 'iso3' => "LIE", 'iso_numeric' => "438", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Lithuania", 'iso2' => "LT", 'iso3' => "LTU", 'iso_numeric' => "440", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Luxembourg", 'iso2' => "LU", 'iso3' => "LUX", 'iso_numeric' => "442", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Macao", 'iso2' => "MO", 'iso3' => "MAC", 'iso_numeric' => "446", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Macedonia (the former Yugoslav Republic of)", 'iso2' => "MK", 'iso3' => "MKD", 'iso_numeric' => "807", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Madagascar", 'iso2' => "MG", 'iso3' => "MDG", 'iso_numeric' => "450", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Malawi", 'iso2' => "MW", 'iso3' => "MWI", 'iso_numeric' => "454", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Malaysia", 'iso2' => "MY", 'iso3' => "MYS", 'iso_numeric' => "458", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Maldives", 'iso2' => "MV", 'iso3' => "MDV", 'iso_numeric' => "462", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mali", 'iso2' => "ML", 'iso3' => "MLI", 'iso_numeric' => "466", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Malta", 'iso2' => "MT", 'iso3' => "MLT", 'iso_numeric' => "470", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Marshall Islands", 'iso2' => "MH", 'iso3' => "MHL", 'iso_numeric' => "584", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Martinique", 'iso2' => "MQ", 'iso3' => "MTQ", 'iso_numeric' => "474", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mauritania", 'iso2' => "MR", 'iso3' => "MRT", 'iso_numeric' => "478", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mauritius", 'iso2' => "MU", 'iso3' => "MUS", 'iso_numeric' => "480", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mayotte", 'iso2' => "YT", 'iso3' => "MYT", 'iso_numeric' => "175", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mexico", 'iso2' => "MX", 'iso3' => "MEX", 'iso_numeric' => "484", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Micronesia (Federated States of)", 'iso2' => "FM", 'iso3' => "FSM", 'iso_numeric' => "583", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Moldova (Republic of)", 'iso2' => "MD", 'iso3' => "MDA", 'iso_numeric' => "498", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Monaco", 'iso2' => "MC", 'iso3' => "MCO", 'iso_numeric' => "492", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mongolia", 'iso2' => "MN", 'iso3' => "MNG", 'iso_numeric' => "496", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Montenegro", 'iso2' => "ME", 'iso3' => "MNE", 'iso_numeric' => "499", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Montserrat", 'iso2' => "MS", 'iso3' => "MSR", 'iso_numeric' => "500", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Morocco", 'iso2' => "MA", 'iso3' => "MAR", 'iso_numeric' => "504", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Mozambique", 'iso2' => "MZ", 'iso3' => "MOZ", 'iso_numeric' => "508", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Myanmar", 'iso2' => "MM", 'iso3' => "MMR", 'iso_numeric' => "104", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Namibia", 'iso2' => "NA", 'iso3' => "NAM", 'iso_numeric' => "516", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Nauru", 'iso2' => "NR", 'iso3' => "NRU", 'iso_numeric' => "520", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Nepal", 'iso2' => "NP", 'iso3' => "NPL", 'iso_numeric' => "524", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Netherlands", 'iso2' => "NL", 'iso3' => "NLD", 'iso_numeric' => "528", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "New Caledonia", 'iso2' => "NC", 'iso3' => "NCL", 'iso_numeric' => "540", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "New Zealand", 'iso2' => "NZ", 'iso3' => "NZL", 'iso_numeric' => "554", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Nicaragua", 'iso2' => "NI", 'iso3' => "NIC", 'iso_numeric' => "558", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Niger", 'iso2' => "NE", 'iso3' => "NER", 'iso_numeric' => "562", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Nigeria", 'iso2' => "NG", 'iso3' => "NGA", 'iso_numeric' => "566", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Niue", 'iso2' => "NU", 'iso3' => "NIU", 'iso_numeric' => "570", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Norfolk Island", 'iso2' => "NF", 'iso3' => "NFK", 'iso_numeric' => "574", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Northern Mariana Islands", 'iso2' => "MP", 'iso3' => "MNP", 'iso_numeric' => "580", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Norway", 'iso2' => "NO", 'iso3' => "NOR", 'iso_numeric' => "578", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Oman", 'iso2' => "OM", 'iso3' => "OMN", 'iso_numeric' => "512", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Pakistan", 'iso2' => "PK", 'iso3' => "PAK", 'iso_numeric' => "586", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Palau", 'iso2' => "PW", 'iso3' => "PLW", 'iso_numeric' => "585", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Palestine, 'iso2' => State of", 'iso2' => "PS", 'iso3' => "PSE", 'iso_numeric' => "275", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Panama", 'iso2' => "PA", 'iso3' => "PAN", 'iso_numeric' => "591", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Papua New Guinea", 'iso2' => "PG", 'iso3' => "PNG", 'iso_numeric' => "598", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Paraguay", 'iso2' => "PY", 'iso3' => "PRY", 'iso_numeric' => "600", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Peru", 'iso2' => "PE", 'iso3' => "PER", 'iso_numeric' => "604", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Philippines", 'iso2' => "PH", 'iso3' => "PHL", 'iso_numeric' => "608", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Pitcairn", 'iso2' => "PN", 'iso3' => "PCN", 'iso_numeric' => "612", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Poland", 'iso2' => "PL", 'iso3' => "POL", 'iso_numeric' => "616", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Portugal", 'iso2' => "PT", 'iso3' => "PRT", 'iso_numeric' => "620", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Puerto Rico", 'iso2' => "PR", 'iso3' => "PRI", 'iso_numeric' => "630", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Qatar", 'iso2' => "QA", 'iso3' => "QAT", 'iso_numeric' => "634", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Réunion", 'iso2' => "RE", 'iso3' => "REU", 'iso_numeric' => "638", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Romania", 'iso2' => "RO", 'iso3' => "ROU", 'iso_numeric' => "642", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Russian Federation", 'iso2' => "RU", 'iso3' => "RUS", 'iso_numeric' => "643", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Rwanda", 'iso2' => "RW", 'iso3' => "RWA", 'iso_numeric' => "646", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Barthélemy", 'iso2' => "BL", 'iso3' => "BLM", 'iso_numeric' => "652", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Helena, 'iso2' => Ascension and Tristan da Cunha", 'iso2' => "SH", 'iso3' => "SHN", 'iso_numeric' => "654", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Kitts and Nevis", 'iso2' => "KN", 'iso3' => "KNA", 'iso_numeric' => "659", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Lucia", 'iso2' => "LC", 'iso3' => "LCA", 'iso_numeric' => "662", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Martin (French part)", 'iso2' => "MF", 'iso3' => "MAF", 'iso_numeric' => "663", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Pierre and Miquelon", 'iso2' => "PM", 'iso3' => "SPM", 'iso_numeric' => "666", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saint Vincent and the Grenadines", 'iso2' => "VC", 'iso3' => "VCT", 'iso_numeric' => "670", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Samoa", 'iso2' => "WS", 'iso3' => "WSM", 'iso_numeric' => "882", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "San Marino", 'iso2' => "SM", 'iso3' => "SMR", 'iso_numeric' => "674", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sao Tome and Principe", 'iso2' => "ST", 'iso3' => "STP", 'iso_numeric' => "678", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Saudi Arabia", 'iso2' => "SA", 'iso3' => "SAU", 'iso_numeric' => "682", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Senegal", 'iso2' => "SN", 'iso3' => "SEN", 'iso_numeric' => "686", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Serbia", 'iso2' => "RS", 'iso3' => "SRB", 'iso_numeric' => "688", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Seychelles", 'iso2' => "SC", 'iso3' => "SYC", 'iso_numeric' => "690", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sierra Leone", 'iso2' => "SL", 'iso3' => "SLE", 'iso_numeric' => "694", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Singapore", 'iso2' => "SG", 'iso3' => "SGP", 'iso_numeric' => "702", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sint Maarten (Dutch part)", 'iso2' => "SX", 'iso3' => "SXM", 'iso_numeric' => "534", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Slovakia", 'iso2' => "SK", 'iso3' => "SVK", 'iso_numeric' => "703", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Slovenia", 'iso2' => "SI", 'iso3' => "SVN", 'iso_numeric' => "705", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Solomon Islands", 'iso2' => "SB", 'iso3' => "SLB", 'iso_numeric' => "090", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Somalia", 'iso2' => "SO", 'iso3' => "SOM", 'iso_numeric' => "706", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "South Africa", 'iso2' => "ZA", 'iso3' => "ZAF", 'iso_numeric' => "710", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "South Georgia and the South Sandwich Islands", 'iso2' => "GS", 'iso3' => "SGS", 'iso_numeric' => "239", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "South Sudan", 'iso2' => "SS", 'iso3' => "SSD", 'iso_numeric' => "728", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Spain", 'iso2' => "ES", 'iso3' => "ESP", 'iso_numeric' => "724", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sri Lanka", 'iso2' => "LK", 'iso3' => "LKA", 'iso_numeric' => "144", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sudan", 'iso2' => "SD", 'iso3' => "SDN", 'iso_numeric' => "729", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Suriname", 'iso2' => "SR", 'iso3' => "SUR", 'iso_numeric' => "740", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Svalbard and Jan Mayen", 'iso2' => "SJ", 'iso3' => "SJM", 'iso_numeric' => "744", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Swaziland", 'iso2' => "SZ", 'iso3' => "SWZ", 'iso_numeric' => "748", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Sweden", 'iso2' => "SE", 'iso3' => "SWE", 'iso_numeric' => "752", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Switzerland", 'iso2' => "CH", 'iso3' => "CHE", 'iso_numeric' => "756", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Syrian Arab Republic", 'iso2' => "SY", 'iso3' => "SYR", 'iso_numeric' => "760", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Taiwan, 'iso2' => Province of China[a]", 'iso2' => "TW", 'iso3' => "TWN", 'iso_numeric' => "158", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tajikistan", 'iso2' => "TJ", 'iso3' => "TJK", 'iso_numeric' => "762", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tanzania, 'iso2' => United Republic of", 'iso2' => "TZ", 'iso3' => "TZA", 'iso_numeric' => "834", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Thailand", 'iso2' => "TH", 'iso3' => "THA", 'iso_numeric' => "764", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Timor-Leste", 'iso2' => "TL", 'iso3' => "TLS", 'iso_numeric' => "626", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Togo", 'iso2' => "TG", 'iso3' => "TGO", 'iso_numeric' => "768", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tokelau", 'iso2' => "TK", 'iso3' => "TKL", 'iso_numeric' => "772", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tonga", 'iso2' => "TO", 'iso3' => "TON", 'iso_numeric' => "776", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Trinidad and Tobago", 'iso2' => "TT", 'iso3' => "TTO", 'iso_numeric' => "780", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tunisia", 'iso2' => "TN", 'iso3' => "TUN", 'iso_numeric' => "788", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Turkey", 'iso2' => "TR", 'iso3' => "TUR", 'iso_numeric' => "792", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Turkmenistan", 'iso2' => "TM", 'iso3' => "TKM", 'iso_numeric' => "795", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Turks and Caicos Islands", 'iso2' => "TC", 'iso3' => "TCA", 'iso_numeric' => "796", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Tuvalu", 'iso2' => "TV", 'iso3' => "TUV", 'iso_numeric' => "798", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Uganda", 'iso2' => "UG", 'iso3' => "UGA", 'iso_numeric' => "800", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Ukraine", 'iso2' => "UA", 'iso3' => "UKR", 'iso_numeric' => "804", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "United Arab Emirates", 'iso2' => "AE", 'iso3' => "ARE", 'iso_numeric' => "784", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "United Kingdom of Great Britain and Northern Ireland", 'iso2' => "GB", 'iso3' => "GBR", 'iso_numeric' => "826", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "United States of America", 'iso2' => "US", 'iso3' => "USA", 'iso_numeric' => "840", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "United States Minor Outlying Islands", 'iso2' => "UM", 'iso3' => "UMI", 'iso_numeric' => "581", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Uruguay", 'iso2' => "UY", 'iso3' => "URY", 'iso_numeric' => "858", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Uzbekistan", 'iso2' => "UZ", 'iso3' => "UZB", 'iso_numeric' => "860", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Vanuatu", 'iso2' => "VU", 'iso3' => "VUT", 'iso_numeric' => "548", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Venezuela (Bolivarian Republic of)", 'iso2' => "VE", 'iso3' => "VEN", 'iso_numeric' => "862", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Viet Nam", 'iso2' => "VN", 'iso3' => "VNM", 'iso_numeric' => "704", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Virgin Islands (British)", 'iso2' => "VG", 'iso3' => "VGB", 'iso_numeric' => "092", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Virgin Islands (U.S.)", 'iso2' => "VI", 'iso3' => "VIR", 'iso_numeric' => "850", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Wallis and Futuna", 'iso2' => "WF", 'iso3' => "WLF", 'iso_numeric' => "876", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Western Sahara", 'iso2' => "EH", 'iso3' => "ESH", 'iso_numeric' => "732", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Yemen", 'iso2' => "YE", 'iso3' => "YEM", 'iso_numeric' => "887", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Zambia", 'iso2' => "ZM", 'iso3' => "ZMB", 'iso_numeric' => "894", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString],
            ['name' => "Zimbabwe", 'iso2' => "ZW", 'iso3' => "ZWE", 'iso_numeric' => "716", 'active'=>true, 'created_at'=>$dateString, 'updated_at'=>$dateString]
        ];

        foreach($countries as $country){
            $this->connection->insert('Countries', $country);
        }
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}
