services:
  payproapi.create_account_request_service:
    class: AppBundle\Service\AccountRequest\CreateAccountRequestService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Account')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Agreement')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Country')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@validator"
      - "@payproapi.mailing_service"