services:
  payproapi.app_version.check_android_service:
    class: AppBundle\Service\AppVersion\CheckAndroidAppVersionService
    arguments:
    - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:AppVersion')"

  payproapi.app_version.check_ios_service:
    class: AppBundle\Service\AppVersion\CheckIOSAppVersionService
    arguments:
    - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:AppVersion')"