services:
  bitcoin_wallet_api_client.process_service:
    class: AppBundle\Service\BitcoinWalletApiClient\BitcoreWalletProcessService
    arguments:
      - "%bitcoin_docker_compose_path%"

  bitcoin_wallet_api_client.wallet_service:
    class: AppBundle\Service\BitcoinWalletApiClient\Wallet
    arguments:
      - "@bitcoin_wallet_api_client.process_service"

  bitcoin_wallet_api_client.transaction_service:
    class: AppBundle\Service\BitcoinWalletApiClient\Transaction
    arguments:
      - "@bitcoin_wallet_api_client.process_service"
