services:
  payproapi.create_bitcoin_account_service:
    class: AppBundle\Service\BitcoinAccount\CreateAccountService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:BitcoinAccount')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@validator"
      - "@bitcoin_wallet_api_client.wallet_service"
  payproapi.get_bitcoin_wallet_service:
    class: AppBundle\Service\BitcoinWallet\GetBitcoinWalletService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@bitcoin_wallet_api_client.wallet_service"
