services:
  payproapi.get_bitcoin_wallet_service:
    class: AppBundle\Service\BitcoinTransaction\CreateTransactionService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@bitcoin_wallet_api_client.wallet_service"
