services:
  bitcoin_wallet_api_client.wallet_service:
    class: AppBundle\Service\BitcoinWalletApiClient\Mock\Wallet

  bitcoin_wallet_api_client.transaction_service:
    class: AppBundle\Service\BitcoinWalletApiClient\Mock\Transaction
    arguments:
      - "@bitcoin_wallet_api_client.hashing_service"

  bitcoin_wallet_api_client.hashing_service:
    class:  AppBundle\Service\BitcoinWalletApiClient\HashingService


