services:
  contis_api_client.request_service:
    class: AppBundle\Service\ContisApiClient\RequestService
    arguments:
      - "%contis_api_host%"

  contis_api_client.hashing_service:
    class: AppBundle\Service\ContisApiClient\HashingService
    arguments:
      - "@session"

  contis_api_client.authentication_service:
    class: AppBundle\Service\ContisApiClient\AuthenticationService
    arguments:
      - "@session"
      - "@contis_api_client.request_service"
      - "@contis_api_client.hashing_service"
      - "%contis_api_host%"
      - "%contis_username%"
      - "%contis_password%"

  contis_api_client.account_service:
    class: AppBundle\Service\ContisApiClient\Account
    arguments:
      - "@contis_api_client.request_service"
      - "@contis_api_client.hashing_service"
      - "@contis_api_client.authentication_service"
