services:
  payproapi.contis_request_service:
    class: AppBundle\Service\Contis\RequestService
    arguments:
      - "@session"
      - "%contis_api_host%"
      - "%contis_hash_pan_key%"
      - "%contis_username%"
      - "%contis_password%"
