services:
  payproapi.create_account_service:
    class: AppBundle\Service\Account\CreateAccountService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Agreement')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Country')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Account')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@validator"
      - "@contis_api_client.account_service"
    
  payproapi.create_mobile_verification_code_service:
    class: AppBundle\Service\MobileVerificationCode\CreateMobileVerificationCodeService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@event_dispatcher"

  payproapi.contact_list_service:
    class: AppBundle\Service\Contact\ContactListService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
