services:
  payproapi.account_manager:
    class: AppBundle\Service\PayPro\AccountManager
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Agreement')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Country')"
      - "@validator"
      - "%contis_wsdl_url%"
