services:
  payproapi.create_notification_service:
    class: AppBundle\Service\Account\CreateNotificationService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Account')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Notification')"
      - "@validator"
