services:
  payproapi.create_profile_service:
    class: AppBundle\Service\Profile\CreateProfileService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Profile')"

  payproapi.update_profile_service:
    class: AppBundle\Service\Profile\UpdateProfileService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Profile')"
