services:
    payproapi.registration_form:
        class: UserBundle\Form\Type\RegistrationFormType
        arguments:
            - AppBundle\Entity\User
        tags:
            - { name: form.type, alias: app_user_registration }

    payproapi.registration_success_subscriber:
        class: UserBundle\EventSubscriber\RegistrationSuccessSubscriber
        arguments: 
            - '@router'
            - '@lexik_jwt_authentication.jwt_manager'
        tags:
            - { name: kernel.event_subscriber }

    payproapi.kernel_request_subscriber:
        class: AppBundle\EventSubscriber\KernelRequestSubscriber
        tags:
            - { name: kernel.event_subscriber }

    payproapi.http_client:
        class: AppBundle\Service\GuzzleHttpClient
