services:
  payproapi.registration_form:
    class: UserBundle\Form\Type\RegistrationFormType
    arguments:
      - AppBundle\Entity\User
    tags:
      - { name: form.type, alias: app_user_registration }

  payproapi.twilio_short_message_service:
    class: AppBundle\Service\TwilioShortMessageService
    arguments:
      - "%twilio_account_id%"
      - "%twilio_auth_token%"
      - "%twilio_phone_number%"

  payproapi.phone_number_validation_service:
    class: AppBundle\Service\PhoneNumberValidatorService

  payproapi.mailing_service:
    class: AppBundle\Service\MailingService
    arguments:
      - "%mailer_user%"
      - "%user_administrator_email%"
      - "@mailer"

imports:
  - { resource: account.yml }
  - { resource: accountRequest.yml }
  - { resource: card.yml }
  - { resource: balance.yml }
  - { resource: cardHolder.yml }
  - { resource: contact.yml }
  - { resource: contis.yml }
  - { resource: mobileVerificationCode.yml }
  - { resource: notification.yml }
  - { resource: profile.yml }
  - { resource: subscribers.yml }
  - { resource: transaction.yml }
  - { resource: user.yml }
  - { resource: user.yml }
  - { resource: bitcoinWalletApiClient.yml }
  - { resource: bitcoinTransaction.yml }
