services:
    payproapi.registration_form:
        class: UserBundle\Form\Type\RegistrationFormType
        arguments:
            - AppBundle\Entity\User
        tags:
            - { name: form.type, alias: app_user_registration }

    payproapi.registration_success_subscriber:
        class: UserBundle\EventSubscriber\RegistrationSuccessSubscriber
        arguments: 
            - '@router'
            - '@lexik_jwt_authentication.jwt_manager'
        tags:
            - { name: kernel.event_subscriber }

    payproapi.kernel_request_subscriber:
        class: AppBundle\EventSubscriber\KernelRequestSubscriber
        tags:
            - { name: kernel.event_subscriber }

    payproapi.notifications_pusher:
        class: AppBundle\Service\NotificationPusher
        arguments:
            - '%push_notifications_config%'

    payproapi.brute_force:
        class: AppBundle\Service\BruteForce
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%brute_force_config%'

    payproapi.event.authentication_failure_listener:
        class: AppBundle\EventListener\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
        arguments:
            - '@payproapi.brute_force'

    payproapi.access_control:
        class: AppBundle\EventListener\AccessControlListener
        arguments:
            - '@payproapi.brute_force'
        tags:
            - { name: kernel.event_subscriber }
