services:
  payproapi.transaction_index_service:
    class: AppBundle\Service\Account\IndexTransactionService
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Transaction')"
      - "@contis_api_client.transaction_service"